### ISSUE TITLE
[Epic] 5.2: Contract migrations

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/contracts#97]
**Epic label**: `E:5.2 Contract Migrations`
**Planned start date**: 2024-01-14
**Due date**: 2024-03-31

# Summary

Migrate all existing smart contract repositories to a `core` / `periphery` / `governance` logical separation of concerns. 

# Acceptance Criteria

Upon completion of this Epic, the following must be satisfied:

- [ ] All smart contract repositories follow the standards defined by cowprotocol/pm#31 
- [ ] No extraneous smart contract repositories
- [ ] NPM packages and dependencies updated

# Tasks

- [ ] chore: forgify `contracts`
  - [ ] cowprotocol/pm#65
  - [ ] cowprotocol/pm#66
  - [ ] cowprotocol/pm#67
  - [ ] cowprotocol/pm#68
  - [ ] cowprotocol/pm#69
  - [ ] cowprotocol/pm#70
  - [ ] cowprotocol/pm#71
  - [ ] cowprotocol/pm#72
  - [ ] cowprotocol/pm#73
  - [ ] cowprotocol/pm#74
  - [ ] cowprotocol/pm#75
- [ ] chore(core): migrate bench to alloy + anvil
- [ ] chore: configure `contracts-periphery` repository
- [ ] chore: migrate rest of contracts to `contracts-periphery`
  - [ ] chore: migrate `HooksTrampoline`
  - [ ] chore: migrate `ComposableCoW`
  - [ ] chore: apply test harness from `contracts-core`
  - [ ] chore: publish npm packages
